//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodimax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int Id { get; set; }
        public int Cine { get; set; }
        public int Empleado { get; set; }
        public int Pelicula { get; set; }
        public int Sala { get; set; }
        public int Boletos { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
    
        public virtual Cine Cine1 { get; set; }
        public virtual Pelicula Pelicula1 { get; set; }
        public virtual Sala Sala1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
